import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useSpring, animated, useScroll } from "@react-spring/web";

import styles from "@/styles/Home.module.scss";
import { MutableRefObject, useRef } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [opProps, opApi] = useSpring(
    () => ({
      from: { opacity: 1 },
      to: { opacity: 1 },
    }),
    []
  );

  const { scrollYProgress } = useScroll({
    onChange: ({ value: { scrollYProgress } }) => {
      if (scrollYProgress > 0.2) {
        opApi.start({ opacity: 0 });
      } else if (scrollYProgress > 0.4) {
      } else if (scrollYProgress > 0.6) {
      } else if (scrollYProgress > 0.8) {
      } else {
        // Default values
        opApi.start({ opacity: 1 });
      }
    },
    default: {
      immediate: true,
    },
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <animated.div style={opProps} className={styles.launchSection}>
            <div className={styles.launchSection__leftSide}>
              <span className={styles.title}>
                <h5> Hi, Im </h5> <h1> Jhonatan </h1>
              </span>
              <span className={styles.description}></span>
            </div>
            <div className={styles.launchSection__rightSide}>
              <div className={styles.launchSection__rightSide__image}>
                <Image src="/images/launch.svg" alt="Picture of the author" width={500} height={500} />
              </div>
            </div>
          </animated.div>
        </div>
      </main>
    </>
  );
}
